A_DIR_MODULES_CLIENT_FREE_QML_COMPONENTS = $$PWD/QMLComponents
A_PRI_MODULES_CLIENT_FREE_QML_COMPONENTS = $$A_DIR_MODULES_CLIENT_FREE_QML_COMPONENTS/QMLComponents.pri
exists($$A_PRI_MODULES_CLIENT_FREE_QML_COMPONENTS) {
	include($$A_PRI_MODULES_CLIENT_FREE_QML_COMPONENTS)
} else {
	error(No ClientFree Module QMLComponents config file $$A_PRI_MODULES_CLIENT_FREE_QML_COMPONENTS)
}

A_DIR_MODULES_CLIENT_FREE_BACKEND = $$PWD/Backend
A_PRI_MODULES_CLIENT_FREE_BACKEND = $$A_DIR_MODULES_CLIENT_FREE_BACKEND/Backend.pri
exists($$A_PRI_MODULES_CLIENT_FREE_BACKEND) {
	include($$A_PRI_MODULES_CLIENT_FREE_BACKEND)
} else {
	error(No ClientFree Module Backend config file $$A_PRI_MODULES_CLIENT_FREE_BACKEND)
}
